
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
            # limits are grater than or equal to requests
          limits:
            cpu: 100m
            memory: 128Mi

---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace:  expense
spec:
  selector:
    app: frontend
    tier: api
    project: expense
  ports:
  - name: frontend-port
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port
